AllCops:
  Exclude:
    - db/schema.rb   
    - 'bin/**/*' 
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/*'
    - 'test/**/*'
    - '*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
